
alias i3conf='vim ~/.config/i3/config'
alias polyconf='ranger ~/.config/polybar/'
alias piconf='vim ~/.config/picom/picom.conf'
alias ri3='i3-msg reload ; i3-msg restart'
alias logoff='sudo pkill -u $USER'
alias alaconf='vim ~/.config/alacritty/alacritty.toml'
alias twow='wine $HOME/turtle/VanillaFixes.exe'
alias zconf='vim ~/.zshrc'
alias zenv='vim ~/.zshenv'
alias szenv='source ~/.zshenv'
alias sozsh='source ~/.zshrc'
alias notes='ranger $HOME/buhfur.github.io/notes'
alias todo='vim $HOME/buhfur.github.io/todo/todo.md -p $HOME/buhfur.github.io/todo/wowtodo.md '
alias updg='sudo apt -y update && sudo apt -y upgrade'
alias roficonf='ranger ~/.config/rofi'
alias rls='sudo systemctl daemon-reload'
alias sys='sudo systemctl'
alias gp='git status && git pull && git add . && git commit -am"Auto Commit: $(date)" && git push'
# SSH aliases
alias proxmox='ssh root@proxmox'
alias mediaserver='ssh media-user@media-server'
alias buhfurpc='ssh buhfur@buhfur-pc'
alias hist='history'
alias disc='discordo'
