
alias i3conf='vim ~/.config/i3/config'
alias polyconf='ranger ~/.config/polybar/'
alias piconf='vim ~/.config/picom/picom.conf'
alias ri3='i3-msg reload ; i3-msg restart'
alias logoff='sudo pkill -u sky'
alias twow='wine $HOME/turtle/VanillaFixes.exe'
alias zconf='vim ~/.zshrc'
alias sozsh='source ~/.zshrc'
alias gp='git add . && git commit -a && git push' 
alias updg='sudo apt update && sudo apt -y upgrade'
alias todo='ranger $HOME/todo/'
alias notes='ranger /home/buhfur/old-wiki/notes'
alias twow='wine ~/twmoa_1171/WoW_tweaked.exe'
alias tserver='ssh torrent-user@torrent-server'
alias minecraft='bash /home/buhfur/UltimMC/UltimMC'
alias weather='curl sky.webionite.com/f/FortWayne'
alias zenv='vim ~/.zshenv'
alias soenv='source ~/.zshenv'
alias relog='sudo pkill -u buhfur'
alias skylarpc='ssh skylar@skylar-pc'
alias sys='sudo systemctl'
alias mcbackups='ls /mnt/backups/backups/minecraft-backups && du -sh /mnt/backups/backups/minecraft-backups'
alias caps='xmodmap ~/.Xmodmap'
alias backups='cd /mnt/backups/backups/'
alias ls='ls -l -h'


export todo='$HOME/todo/'
export backups='/mnt/backups/backups/'
